routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('todo', 'Todos\TodoController');
    Route::put('todo/{todo}/complete', 'Todos\MarkTodoCompletedController@update')
        ->name('todo.complete');
});

app/Todo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Todo extends Model
{
    /**
     * Attributes that can be mass assigned (filled)
     *
     * @var array
     */
    public $fillable = [
        'user_id',
        'title',
        'due_at',
        'description',
    ];

    /**
     * Date fields
     *
     * @var array
     */
    public $dates = [
        'due_at',
        'completed_at',
    ];

    public function user()
    {
        return $this->belongsTo(\App\User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/Todos/MarkTodoCompletedController.php
<?php

namespace App\Http\Controllers\Todos;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Todo;
use App\Jobs\Todos\MarkTodoCompleted;

class MarkTodoCompletedController extends Controller
{

    /**
     * Method to mark a todo as completed
     *
     * @param Request $request
     * @param Todo $todo
     * @return void
     */
    public function update(Request $request, Todo $todo)
    {
        // Check if the user can update the todo
        $this->authorize('update', $todo);

        // Mark the todo completed
        dispatch_now(new MarkTodoCompleted($todo, $request->user()));

        // Return back to previous page
        return redirect()->back()->with('successMessage', __('Todo completed.'));
    }
}

app/Http/Controllers/Todos/TodoController.php
<?php

namespace App\Http\Controllers\Todos;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Todos\SaveTodoRequest;
use App\Todo;
use App\Jobs\Todos\CreateTodo;
use App\Repositories\Contracts\TodoRepositoryInterface;
use App\Transformers\Todos\SimpleTodoTransformer;

class TodoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(TodoRepositoryInterface $todoRepo, SimpleTodoTransformer $transformer)
    {
        //dd($transformer->transformCollection($todoRepo->allPending(auth()->user())));
        return view('todos.index', [
            'todos' => $transformer->transformCollection($todoRepo->allPending(auth()->user()))
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Todo::class);

        return view('todos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Todos\SaveTodoRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SaveTodoRequest $request)
    {
        $this->authorize('create', Todo::class);

        // Response will always be going back to the previous page
        $response = redirect()->back();

        // Create the todo and redirect to previous page with a success message
        if (dispatch_now(new CreateTodo($request->all(), $request->user()))) {
            return $response->with('successMessage', __('Todo has been added.'));
        }

        // Todo creation failed, redirect back with an error message
        return $response->with('errorMessage', __('There was an error in adding the Todo.'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">Dashboard</div>

            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                @endif

                You are logged in!
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    Todos <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('todo.index') }}">
                                        {{ __('List') }}
                                    </a>
                                    <a class="dropdown-item" href="{{ route('todo.create') }}">
                                            {{ __('Add') }}
                                    </a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="container">
                @if (session('successMessage'))
                    <div class="alert alert-success">
                        {{ session('successMessage') }}
                    </div>
                @endif
                @if (session('errorMessage'))
                    <div class="alert alert-danger">
                        {{ session('errorMessage') }}
                    </div>
                @endif
                @yield('content')
            </div>
        </main>
    </div>
</body>
</html>

resources/views/partials/form/errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/todos/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">Dashboard</div>
            <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                @endif
                @include('partials.form.errors')
                <form method="POST" action="{{ route('todo.store') }}">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ __('Title') }}</label>
                        <input type="text"
                            class="form-control"
                            name="title"
                            id="exampleInputEmail1" aria-describedby="emailHelp"
                            placeholder="{{ __('Title') }}"
                            value="{{ old('title') }}">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">{{ __('Desscription') }}</label>
                        <textarea class="form-control"
                            name="description"
                            cols="30"
                            rows="3">{{ old('description') }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">{{ __('Due Date') }}</label>
                        <input type="date"
                            class="form-control"
                            placeholder="Due Date"
                            name="due_at"
                            value="{{ old('due_at') }}">
                    </div>
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/todos/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">Todos</div>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Title</th>
                            <th scope="col">Due At</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($todos as $todo)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $todo->title }}</td>
                                <td>{{ $todo->due_at ?  $todo->due_at->format('j, M Y') : ''}}</td>
                                <td>
                                    <a href="{{ route('todo.complete', ['todo' => $todo->id]) }}"
                                       onclick="event.preventDefault();
                                       document.getElementById('todo-complete-form-{{ $todo->id }}').submit();">
                                        {{ __('Complete') }}
                                    </a> |
                                    <a href="#">{{ __('Delete') }}</a>
                                    <form id="todo-complete-form-{{ $todo->id }}"
                                        action="{{ route('todo.complete', ['todo' => $todo->id]) }}" method="POST" style="display: none;">
                                            {{ method_field('PUT') }}
                                            @csrf
                                        </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
            </div>
        </div>
    </div>
</div>
@endsection